services:
  ticket-io_backend:
    build:
      context: .
      dockerfile: dockerfile.ticket-io_backend
    container_name: ticket-io_backend
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - ticket-io_mysql

  ticket-io_mysql:
    image: mysql:latest
    container_name: ticket-io_mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin!
      MYSQL_DATABASE: main
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

volumes:
  mysql_data:
