services:
  gin-api:
    build:
      context: .
      dockerfile: dockerfile
    container_name: gin-api
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - gin-mysql

  gin-mysql:
    image: mysql:latest
    container_name: gin-mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin!
      MYSQL_DATABASE: main
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

volumes:
  mysql_data:
